language: node_js
node_js:
  - "0.12"
# command to install dependencies
install:
  - cd ./hexo
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
# command to run tests
script:
  - chmod +x ./build.sh
  - ./build.sh
branches:
  only:
    - raw
