menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/u/2393492311
    GitHub: https://github.com/sumimakito
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: blogkeepmoe

# Analytics
# google-analytics:
ga: UA-73442912-1
# baidu-analytics:
ba:

# Copyright Infomation
startyear: 2014

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
