# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Miscellaneous
google_analytics: UA-73442912-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
